# Generated by Django 4.1.3 on 2022-11-20 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompostCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('members_count', models.IntegerField(verbose_name='Members living in the household')),
                ('green_land_size', models.IntegerField(verbose_name='Green land size (m2)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Composter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(verbose_name='Composter capacity in liters')),
                ('fill_amount', models.IntegerField(verbose_name='Composter fill amount in liters')),
                ('categories', models.ManyToManyField(related_name='composters', related_query_name='composter', to='compost.compostcategory')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compost.household')),
            ],
        ),
    ]
