# Generated by Django 4.1.3 on 2022-11-20 08:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('compost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposterAction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fill_amount', models.IntegerField(verbose_name='Composter fill amount after action')),
                ('action_type', models.CharField(choices=[('fill', 'Fill'), ('empty', 'Empty')], max_length=5)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compost.compostcategory')),
                ('composter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compost.composter')),
            ],
        ),
    ]
