# Generated by Django 4.1.3 on 2022-11-20 09:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('compost', '0002_composteraction_compostaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composter',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='composters', related_query_name='composter', to='compost.compostcategory'),
        ),
        migrations.AlterField(
            model_name='composter',
            name='fill_amount',
            field=models.IntegerField(blank=True, verbose_name='Composter fill amount in liters'),
        ),
        migrations.CreateModel(
            name='CompostAudit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recorded_density', models.FloatField(blank=True)),
                ('composter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compost.composter')),
            ],
        ),
    ]
